-- ============================================
-- SOLUCIÓN FINAL: Importar datos en t_computo_observaciones
-- ============================================
-- 
-- Si Supabase Dashboard sigue validando el CSV antes de insertar,
-- esta solución crea una función que maneja las cadenas vacías
-- ============================================

-- PASO 1: Asegurar que id_equipo_computo es TEXT y permite NULL
ALTER TABLE public.t_computo_observaciones 
ALTER COLUMN id_equipo_computo TYPE TEXT USING id_equipo_computo::TEXT;

ALTER TABLE public.t_computo_observaciones 
ALTER COLUMN id_equipo_computo DROP NOT NULL;

-- PASO 2: Asegurar que id_observacion es GENERATED BY DEFAULT
ALTER TABLE public.t_computo_observaciones 
ALTER COLUMN id_observacion SET GENERATED BY DEFAULT;

-- PASO 3: Eliminar restricciones temporalmente
DROP INDEX IF EXISTS public.idx_computo_observaciones_equipo;
ALTER TABLE public.t_computo_observaciones 
DROP CONSTRAINT IF EXISTS fk_equipo_computo_observaciones;

-- PASO 4: Crear una función que convierta cadenas vacías a NULL automáticamente
CREATE OR REPLACE FUNCTION public.normalizar_id_equipo_computo()
RETURNS TRIGGER AS $$
BEGIN
    -- Convertir cadenas vacías a NULL
    IF NEW.id_equipo_computo = '' OR TRIM(NEW.id_equipo_computo) = '' THEN
        NEW.id_equipo_computo := NULL;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- PASO 5: Crear trigger que ejecute la función antes de insertar
DROP TRIGGER IF EXISTS trigger_normalizar_id_equipo_computo ON public.t_computo_observaciones;

CREATE TRIGGER trigger_normalizar_id_equipo_computo
    BEFORE INSERT OR UPDATE ON public.t_computo_observaciones
    FOR EACH ROW
    EXECUTE FUNCTION public.normalizar_id_equipo_computo();

-- ============================================
-- AHORA INTENTA IMPORTAR DESDE SUPABASE DASHBOARD
-- ============================================
-- El trigger convertirá automáticamente las cadenas vacías a NULL
-- ============================================

-- VERIFICACIÓN
SELECT 
    'Configuración lista para importar' as estado,
    column_name,
    data_type,
    is_nullable
FROM information_schema.columns
WHERE table_schema = 'public' 
  AND table_name = 't_computo_observaciones'
  AND column_name IN ('id_equipo_computo', 'id_observacion')
ORDER BY column_name;



