-- ============================================
-- SOLUCIÓN FORZADA: Importar datos en t_computo_observaciones
-- ============================================
-- 
-- Este script fuerza los cambios necesarios para importar datos
-- Ejecuta TODO este script antes de importar
-- ============================================

-- PASO 1: Cambiar GENERATED ALWAYS a GENERATED BY DEFAULT
ALTER TABLE public.t_computo_observaciones 
ALTER COLUMN id_observacion SET GENERATED BY DEFAULT;

-- PASO 2: Eliminar TODAS las restricciones y índices relacionados
DROP INDEX IF EXISTS public.idx_computo_observaciones_equipo;
ALTER TABLE public.t_computo_observaciones 
DROP CONSTRAINT IF EXISTS fk_equipo_computo_observaciones;

-- PASO 3: Verificar si hay datos y manejarlos
-- Si hay datos, necesitamos convertirlos primero
DO $$
BEGIN
    -- Si la columna ya es TEXT, no hacer nada
    IF EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_schema = 'public' 
          AND table_name = 't_computo_observaciones' 
          AND column_name = 'id_equipo_computo'
          AND data_type = 'text'
    ) THEN
        RAISE NOTICE 'La columna id_equipo_computo ya es TEXT';
    ELSE
        -- Cambiar a TEXT usando una conversión explícita
        ALTER TABLE public.t_computo_observaciones 
        ALTER COLUMN id_equipo_computo TYPE TEXT 
        USING CASE 
            WHEN id_equipo_computo IS NULL THEN NULL
            ELSE id_equipo_computo::TEXT
        END;
    END IF;
END $$;

-- PASO 4: Asegurar que permite NULL
ALTER TABLE public.t_computo_observaciones 
ALTER COLUMN id_equipo_computo DROP NOT NULL;

-- PASO 5: Verificar el estado final
SELECT 
    'Estado de la tabla:' as info,
    column_name,
    data_type,
    is_nullable
FROM information_schema.columns
WHERE table_schema = 'public' 
  AND table_name = 't_computo_observaciones'
  AND column_name IN ('id_equipo_computo', 'id_observacion')
ORDER BY column_name;

-- ============================================
-- AHORA IMPORTA TUS DATOS DESDE SUPABASE DASHBOARD
-- ============================================
-- Ve a Table Editor > t_computo_observaciones > Import data
-- Selecciona tu archivo y importa. Ahora debería funcionar sin errores.
-- ============================================



