-- ============================================
-- SOLUCIÓN RÁPIDA: Importar datos en t_computo_observaciones
-- ============================================
-- 
-- Ejecuta estos comandos UNO POR UNO o todos juntos ANTES de importar
-- ============================================

-- PASO 1: Cambiar GENERATED ALWAYS a GENERATED BY DEFAULT
-- Esto permite importar datos con valores NULL en id_observacion
ALTER TABLE public.t_computo_observaciones 
ALTER COLUMN id_observacion SET GENERATED BY DEFAULT;

-- PASO 2: Eliminar el índice único y la foreign key temporalmente
DROP INDEX IF EXISTS public.idx_computo_observaciones_equipo;
ALTER TABLE public.t_computo_observaciones 
DROP CONSTRAINT IF EXISTS fk_equipo_computo_observaciones;

-- PASO 3: Cambiar temporalmente id_equipo_computo a TEXT para permitir importar cadenas vacías
ALTER TABLE public.t_computo_observaciones 
ALTER COLUMN id_equipo_computo TYPE TEXT USING id_equipo_computo::TEXT;

-- PASO 4: Permitir NULL en id_equipo_computo
ALTER TABLE public.t_computo_observaciones 
ALTER COLUMN id_equipo_computo DROP NOT NULL;

-- ============================================
-- AHORA IMPORTA TUS DATOS DESDE SUPABASE DASHBOARD
-- ============================================
-- Ve a Table Editor > t_computo_observaciones > Import data
-- Selecciona tu archivo y importa. Ahora debería funcionar sin errores.
-- ============================================










